/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SourcePackages;

import java.sql.PreparedStatement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author ronor
 */
public class Pay_EMI extends javax.swing.JFrame {

    /**
     * Creates new form Pay_EMI
     */
    JDBC db;
    String branch, name, amount,date,time,remain,remainamnt, paid;
    public Pay_EMI(String x, String y) {
        initComponents();
        db=new JDBC();
        branch=y;
        name=x;
        Uname.setText(x);
        Ubranch.setText(y);
        paypnl.setVisible(false);
    }
    public Pay_EMI() {
        initComponents();
    }
    public void dateTime(){
    	DateFormat dateFormat = new SimpleDateFormat("hh.mm aa");
    	time = dateFormat.format(new Date()).toString();
    	DateFormat dateFormat2 = new SimpleDateFormat("dd/MM/yyyy");
    	date = dateFormat2.format(new Date()).toString();
    }
    public void calc(){
        int a =Integer.valueOf(remain);
        int d = Integer.valueOf(paid);
        remain= String.valueOf(a-1);
        paid=String.valueOf(d+1);
        Double b = Double.valueOf(remainamnt);
        Double c=Double.valueOf(amount);
        remainamnt=String.valueOf(b-c);
    }
    public void updateDB(){
        try {
            PreparedStatement Add = db.con.prepareStatement("update emi set eremainmonth=?, eremainprice=?, epaidmonth=? where eid=? and eitem=?");
            Add.setString(1, remain);
            Add.setString(2, remainamnt);
            Add.setString(3, paid);
            Add.setString(4, idEmi.getText());
            Add.setString(5, (String)EMIItems.getSelectedItem());

            Add.executeUpdate();
            fetch();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    public void fetch(){
        try {
                String Query = "select eremainmonth from emi where eid='"+idEmi.getText()+"' and eitem='"+(String)EMIItems.getSelectedItem()+"'";
                String x="";
                db.st = db.con.createStatement();
                db.rs = db.st.executeQuery(Query);
                if(db.rs.next()){
                    x=db.rs.getString("eremainmonth");
                }
                if("0".equals(x)){
                    PreparedStatement Add = db.con.prepareStatement("update emi set estatus=? where eid=? and eitem=?");
                    Add.setString(1, "Paid");
                    Add.setString(2, idEmi.getText());
                    Add.setString(3, (String)EMIItems.getSelectedItem());
                    Stts.setText("Paid");
                    bike4.setVisible(false);
                    Add.executeUpdate();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        Ubranch = new javax.swing.JLabel();
        Uname = new javax.swing.JLabel();
        bike1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        user2 = new javax.swing.JLabel();
        SrchName = new javax.swing.JTextField();
        user3 = new javax.swing.JLabel();
        idEmi = new javax.swing.JTextField();
        user4 = new javax.swing.JLabel();
        EMIItems = new javax.swing.JComboBox<>();
        bike3 = new javax.swing.JButton();
        paypnl = new javax.swing.JPanel();
        user5 = new javax.swing.JLabel();
        user6 = new javax.swing.JLabel();
        user7 = new javax.swing.JLabel();
        user8 = new javax.swing.JLabel();
        user9 = new javax.swing.JLabel();
        timelbl = new javax.swing.JLabel();
        datelbl = new javax.swing.JLabel();
        inm = new javax.swing.JLabel();
        amn = new javax.swing.JLabel();
        enm = new javax.swing.JLabel();
        bike4 = new javax.swing.JButton();
        Stts = new javax.swing.JLabel();
        user10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel5.setBackground(new java.awt.Color(254, 254, 254));

        user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user.setForeground(new java.awt.Color(1, 1, 1));
        user.setText("User : ");

        user1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user1.setForeground(new java.awt.Color(1, 1, 1));
        user1.setText("Branch : ");

        Ubranch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Ubranch.setForeground(new java.awt.Color(1, 1, 1));
        Ubranch.setText("Name...");

        Uname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Uname.setForeground(new java.awt.Color(1, 1, 1));
        Uname.setText("Name...");

        bike1.setBackground(new java.awt.Color(1, 1, 1));
        bike1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bike1.setForeground(new java.awt.Color(255, 255, 255));
        bike1.setText("Back");
        bike1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bike1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("______________________________________________________________________________________");

        user2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user2.setForeground(new java.awt.Color(1, 1, 1));
        user2.setText("Name :");

        SrchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrchNameActionPerformed(evt);
            }
        });

        user3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user3.setForeground(new java.awt.Color(1, 1, 1));
        user3.setText("Aaadhar No :");

        idEmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idEmiActionPerformed(evt);
            }
        });

        user4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user4.setForeground(new java.awt.Color(1, 1, 1));
        user4.setText("EMI Item :");

        EMIItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cycle", "Bike", "Car", "Laptop", "Inverter", "TV", "AC", "Fridge" }));

        bike3.setBackground(new java.awt.Color(1, 1, 1));
        bike3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bike3.setForeground(new java.awt.Color(255, 255, 255));
        bike3.setText("Okay");
        bike3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bike3ActionPerformed(evt);
            }
        });

        user5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user5.setText("Name :");

        user6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user6.setText("Item :");

        user7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user7.setText("Amount :");

        user8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user8.setText("Date :");

        user9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user9.setText("Time :");

        timelbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        timelbl.setText("............");

        datelbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        datelbl.setText("...........");

        inm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inm.setText("............");

        amn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        amn.setText("............");

        enm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enm.setText("..........");

        bike4.setBackground(new java.awt.Color(1, 1, 1));
        bike4.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bike4.setForeground(new java.awt.Color(255, 255, 255));
        bike4.setText("Pay");
        bike4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bike4ActionPerformed(evt);
            }
        });

        Stts.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Stts.setText("............");

        user10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        user10.setText("Status :");

        javax.swing.GroupLayout paypnlLayout = new javax.swing.GroupLayout(paypnl);
        paypnl.setLayout(paypnlLayout);
        paypnlLayout.setHorizontalGroup(
            paypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paypnlLayout.createSequentialGroup()
                .addGroup(paypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paypnlLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(user8, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(datelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(paypnlLayout.createSequentialGroup()
                        .addGroup(paypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paypnlLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(user5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(enm, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paypnlLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(user6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(inm, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paypnlLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(user7)
                                .addGap(6, 6, 6)
                                .addComponent(amn, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paypnlLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(user9, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(timelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paypnlLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(bike4))
                            .addGroup(paypnlLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(user10, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Stts, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paypnlLayout.setVerticalGroup(
            paypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paypnlLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(paypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user5)
                    .addComponent(enm))
                .addGap(6, 6, 6)
                .addGroup(paypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user6)
                    .addComponent(inm))
                .addGap(6, 6, 6)
                .addGroup(paypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user7)
                    .addComponent(amn))
                .addGap(6, 6, 6)
                .addGroup(paypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user8)
                    .addComponent(datelbl))
                .addGap(6, 6, 6)
                .addGroup(paypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user9)
                    .addComponent(timelbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paypnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(user10)
                    .addComponent(Stts))
                .addGap(27, 27, 27)
                .addComponent(bike4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(66, 99, 235));

        jButton8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8jButton7ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Engineers Microfinance Services");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-bank-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(22, 22, 22))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(165, 165, 165))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(135, 135, 135))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(user3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SrchName, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idEmi, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EMIItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bike3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paypnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(user1)
                                .addGap(6, 6, 6)
                                .addComponent(Ubranch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Uname, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bike1)
                        .addGap(34, 34, 34))))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Uname))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user1)
                            .addComponent(Ubranch)))
                    .addComponent(bike1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(paypnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(user2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(user3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(user4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(SrchName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(idEmi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(EMIItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bike3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(600, 496));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bike1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bike1ActionPerformed
        new MainMenu(name,branch).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bike1ActionPerformed

    private void SrchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SrchNameActionPerformed

    private void idEmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idEmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idEmiActionPerformed

    private void bike3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bike3ActionPerformed
         if(SrchName.getText().isEmpty() && idEmi.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Enter The Aadhar Number / Name.");
        }else{
            try {
                String Query = "select * from emi where eid='"+idEmi.getText()+"' and eitem='"+(String)EMIItems.getSelectedItem()+"'";
                
                db.st = db.con.createStatement();
                db.rs = db.st.executeQuery(Query);
                if(db.rs.next()){
                    enm.setText(db.rs.getString("ename"));
                    inm.setText(db.rs.getString("eitem"));
                    amn.setText(db.rs.getString("einstalment"));
                    Stts.setText(db.rs.getString("estatus"));
                    if(Stts.getText().equals("Paid")){
                        bike4.setVisible(false);
                    }
                    amount=db.rs.getString("einstalment");
                    remain=db.rs.getString("eremainmonth");
                    paid=db.rs.getString("epaidmonth");
                    remainamnt=db.rs.getString("eremainprice");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            dateTime();
            calc();
            datelbl.setText(date);
            timelbl.setText(time);
            paypnl.setVisible(true);
        }
    }//GEN-LAST:event_bike3ActionPerformed

    private void bike4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bike4ActionPerformed
        updateDB();
        JOptionPane.showMessageDialog(this, "EMI Paid.");
    }//GEN-LAST:event_bike4ActionPerformed

    private void jButton8jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton8jButton7ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> EMIItems;
    private javax.swing.JTextField SrchName;
    private javax.swing.JLabel Stts;
    private javax.swing.JLabel Ubranch;
    private javax.swing.JLabel Uname;
    private javax.swing.JLabel amn;
    private javax.swing.JButton bike1;
    private javax.swing.JButton bike3;
    private javax.swing.JButton bike4;
    private javax.swing.JLabel datelbl;
    private javax.swing.JLabel enm;
    private javax.swing.JTextField idEmi;
    private javax.swing.JLabel inm;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel paypnl;
    private javax.swing.JLabel timelbl;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user1;
    private javax.swing.JLabel user10;
    private javax.swing.JLabel user2;
    private javax.swing.JLabel user3;
    private javax.swing.JLabel user4;
    private javax.swing.JLabel user5;
    private javax.swing.JLabel user6;
    private javax.swing.JLabel user7;
    private javax.swing.JLabel user8;
    private javax.swing.JLabel user9;
    // End of variables declaration//GEN-END:variables
}
