/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SourcePackages;

import com.itextpdf.kernel.colors.DeviceRgb;
import com.itextpdf.kernel.geom.PageSize;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.borders.Border;
import com.itextpdf.layout.element.Cell;
import com.itextpdf.layout.element.Paragraph;
import com.itextpdf.layout.element.Table;
import com.itextpdf.layout.properties.TextAlignment;
import com.itextpdf.layout.properties.VerticalAlignment;
import java.io.File;
import java.nio.file.Paths;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.icepdf.ri.common.ComponentKeyBinding;
import org.icepdf.ri.common.SwingController;
import org.icepdf.ri.common.SwingViewBuilder;
import com.spire.pdf.PdfDocument;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.FileNotFoundException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;

/**
 *
 * @author mysterio
 */
public class PrintPDF extends javax.swing.JFrame {

    /**
     * Creates new form PrintPDF
     */
    String path,branch,name,mode,date,fName,uuid;
    String info [] = new String[20];
    public PrintPDF() {
        initComponents();
    }
    public PrintPDF(String x,String y,String z[],String w) throws FileNotFoundException {
        initComponents();
        branch=y;
        name=x;
        mode=w;
        for(int i=0; i<z.length; i++){
            info[i]=z[i];
        }
        Time();
        uuidGen();
        createDir();
        writePdf();
        openpdf(path); 
    }
    public void uuidGen() {
        StringBuffer buffer = new StringBuffer();
        Random random = new Random();
        char[] chars = new char[] { 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h',
                'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
                'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F',
                'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
                'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '1', '2', '3', '4',
                '5', '6', '7', '8', '9', '0' };
        for (int i = 0; i < 5; i++) {
            buffer.append(chars[random.nextInt(chars.length)]);
        }
        uuid=buffer.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bike1 = new javax.swing.JButton();
        bike3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        jPanel10.setBackground(new java.awt.Color(66, 99, 235));

        jButton8.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8jButton7ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Engineers Microfinance Services");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-bank-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton8)
                        .addGap(22, 22, 22))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addGap(165, 165, 165))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(135, 135, 135))))
        );

        bike1.setBackground(new java.awt.Color(1, 1, 1));
        bike1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bike1.setForeground(new java.awt.Color(254, 247, 247));
        bike1.setText("Back");
        bike1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bike1ActionPerformed(evt);
            }
        });

        bike3.setBackground(new java.awt.Color(1, 1, 1));
        bike3.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        bike3.setForeground(new java.awt.Color(254, 247, 247));
        bike3.setText("Print Bill");
        bike3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bike3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bike1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bike3))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bike3)
                    .addComponent(bike1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(600, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton8jButton7ActionPerformed

    private void bike1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bike1ActionPerformed
        new MainMenu(name,branch).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bike1ActionPerformed

    private void bike3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bike3ActionPerformed
        printDoc(path);
    }//GEN-LAST:event_bike3ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void Time(){
    	DateFormat dateFormat2 = new SimpleDateFormat("dd-MM-yyyy");
    	date = dateFormat2.format(new Date()).toString();
    }
    
    void createDir() {
        try {
            path = Paths.get(System.getProperty("user.home")).toString();
            String dir = "EMS";
            path += File.separator + dir;
            File f = new File(path);
            if (!f.exists()) {
                f.mkdir();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    public void writePdf() throws FileNotFoundException {
        float col = 280f;
        float colWidth[] = {col, col};
        fName=date+"_"+info[0]+".pdf";
        path += File.separator + fName;
        PdfWriter pw = new PdfWriter(path);
        com.itextpdf.kernel.pdf.PdfDocument pd = new com.itextpdf.kernel.pdf.PdfDocument(pw);
        pd.addNewPage();
        pd.setDefaultPageSize(PageSize.A4);
        Document d = new Document(pd);
        Cell c = new Cell();

        Table tb = new Table(colWidth);

        tb.setBackgroundColor(new DeviceRgb(63, 169, 219))
                .setFontColor(new DeviceRgb(255, 255, 255));

        tb.addCell(new Cell().add(new Paragraph("INVOICE"))
                .setTextAlignment(TextAlignment.CENTER)
                .setVerticalAlignment(VerticalAlignment.MIDDLE)
                .setMarginTop(30f)
                .setMarginBottom(30f)
                .setPaddingBottom(30f)
                .setPaddingTop(30f)
                .setFontSize(30f)
                .setBorder(Border.NO_BORDER)
        );

        tb.addCell(new Cell().add(new Paragraph("Engineers Microfinance Bank\n#Paglachandi, Kaliganj\n284812592002"))
                .setTextAlignment(TextAlignment.RIGHT)
                .setMarginTop(30f)
                .setMarginBottom(30f)
                .setPaddingBottom(30f)
                .setPaddingTop(30f)
                .setPaddingRight(10f)
                .setBorder(Border.NO_BORDER)
        );

        float custColWidth[] = {80, 300, 100, 80};
        Table custTb = new Table(custColWidth);

        custTb.addCell(new Cell(0, 4)
                .add(new Paragraph("\nCustomer Information : "))
                .setBold()
                .setBorder(Border.NO_BORDER)
        );

        custTb.addCell(new Cell().add(new Paragraph("Name : ")).setBorder(Border.NO_BORDER).setBold());
        custTb.addCell(new Cell().add(new Paragraph(""+info[0])).setBorder(Border.NO_BORDER));
        custTb.addCell(new Cell().add(new Paragraph("Invoice No : ")).setBorder(Border.NO_BORDER).setBold());
        custTb.addCell(new Cell().add(new Paragraph("#"+uuid)).setBorder(Border.NO_BORDER));

        custTb.addCell(new Cell().add(new Paragraph("Phone No : ")).setBorder(Border.NO_BORDER).setBold());
        custTb.addCell(new Cell().add(new Paragraph(""+info[2])).setBorder(Border.NO_BORDER));
        custTb.addCell(new Cell().add(new Paragraph("Date : ")).setBorder(Border.NO_BORDER).setBold());
        custTb.addCell(new Cell().add(new Paragraph(""+info[3])).setBorder(Border.NO_BORDER));

        custTb.addCell(new Cell().add(new Paragraph("Aadhar No : ")).setBorder(Border.NO_BORDER).setBold());
        custTb.addCell(new Cell().add(new Paragraph(""+info[1])).setBorder(Border.NO_BORDER));
        custTb.addCell(new Cell().add(new Paragraph("Payment Mode : ")).setBorder(Border.NO_BORDER).setBold());
        custTb.addCell(new Cell().add(new Paragraph("" +mode)).setBorder(Border.NO_BORDER));

        float itemColWidth[] = {140, 140, 140, 140};
        Table itemTb = new Table(itemColWidth);

        itemTb.addCell(new Cell().add(new Paragraph("Item"))
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setVerticalAlignment(VerticalAlignment.MIDDLE)
                .setBackgroundColor(new DeviceRgb(63, 169, 219))
                .setFontColor(new DeviceRgb(255, 255, 255))
        );
        itemTb.addCell(new Cell().add(new Paragraph("Quantity"))
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setVerticalAlignment(VerticalAlignment.MIDDLE)
                .setBackgroundColor(new DeviceRgb(63, 169, 219))
                .setFontColor(new DeviceRgb(255, 255, 255))
        );
        itemTb.addCell(new Cell().add(new Paragraph("MRP (INR)"))
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setVerticalAlignment(VerticalAlignment.MIDDLE)
                .setBackgroundColor(new DeviceRgb(63, 169, 219))
                .setFontColor(new DeviceRgb(255, 255, 255))
        );
        itemTb.addCell(new Cell().add(new Paragraph("Tax (%)"))
                .setBold()
                .setTextAlignment(TextAlignment.CENTER)
                .setVerticalAlignment(VerticalAlignment.MIDDLE)
                .setBackgroundColor(new DeviceRgb(63, 169, 219))
                .setFontColor(new DeviceRgb(255, 255, 255))
        );

        itemTb.addCell(new Cell().add(new Paragraph(""+info[4])));
        itemTb.addCell(new Cell().add(new Paragraph(""+info[6])));
        itemTb.addCell(new Cell().add(new Paragraph(""+info[5])));

        itemTb.addCell(new Cell().add(new Paragraph("18% (GST)")));

        itemTb.addCell(new Cell(0, 3).add(new Paragraph("Total : "))
                .setBold()
                .setTextAlignment(TextAlignment.RIGHT)
                .setBackgroundColor(new DeviceRgb(63, 169, 219))
                .setFontColor(new DeviceRgb(255, 255, 255))
        );
        itemTb.addCell(new Cell().add(new Paragraph(""+info[7]))
                .setBold()
                .setTextAlignment(TextAlignment.RIGHT)
                .setBackgroundColor(new DeviceRgb(63, 169, 219))
                .setFontColor(new DeviceRgb(255, 255, 255))
        );

        d.add(tb);
        d.add(custTb);
        d.add(new Paragraph("\n"));
        d.add(itemTb);
        d.add(new Paragraph("\n"));

        if ("EMI".equals(mode)) {
            Table emiTb = new Table(itemColWidth);

            emiTb.addCell(new Cell().add(new Paragraph("Amount"))
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE)
                    .setBackgroundColor(new DeviceRgb(63, 169, 219))
                    .setFontColor(new DeviceRgb(255, 255, 255))
            );
            emiTb.addCell(new Cell().add(new Paragraph("Interest"))
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE)
                    .setBackgroundColor(new DeviceRgb(63, 169, 219))
                    .setFontColor(new DeviceRgb(255, 255, 255))
            );
            emiTb.addCell(new Cell().add(new Paragraph("Months"))
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE)
                    .setBackgroundColor(new DeviceRgb(63, 169, 219))
                    .setFontColor(new DeviceRgb(255, 255, 255))
            );
            emiTb.addCell(new Cell().add(new Paragraph("EMI"))
                    .setBold()
                    .setTextAlignment(TextAlignment.CENTER)
                    .setVerticalAlignment(VerticalAlignment.MIDDLE)
                    .setBackgroundColor(new DeviceRgb(63, 169, 219))
                    .setFontColor(new DeviceRgb(255, 255, 255))
            );

            emiTb.addCell(new Cell().add(new Paragraph(""+info[7])));
            emiTb.addCell(new Cell().add(new Paragraph(""+info[8])));
            emiTb.addCell(new Cell().add(new Paragraph(""+info[9])));
            emiTb.addCell(new Cell().add(new Paragraph(""+info[10])));

            d.add(emiTb);
        }

        d.add(new Paragraph("\n\n\n\n(Authorized Signatory)").setTextAlignment(TextAlignment.RIGHT).setBold().setItalic().setUnderline());
        d.close();

    }
    
    public void openpdf (String file){
        try {
            SwingController control=new SwingController();
            SwingViewBuilder factry=new SwingViewBuilder(control);
            JPanel veiwerCompntpnl=factry.buildViewerPanel();
            ComponentKeyBinding.install(control, veiwerCompntpnl);
            control.getDocumentViewController().setAnnotationCallback(
                    new org.icepdf.ri.common.MyAnnotationCallback(
                    control.getDocumentViewController()));
                   control.openDocument(file);
        jScrollPane1.setViewportView(veiwerCompntpnl); 
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    public void printDoc(String file){
      PrinterJob printerJob = PrinterJob.getPrinterJob();
        PageFormat pageFormat = printerJob.defaultPage();
        Paper paper = pageFormat.getPaper();
        paper.setImageableArea(0, 0, pageFormat.getWidth(), pageFormat.getHeight());
        pageFormat.setPaper(paper);
        PdfDocument pdf = new PdfDocument();
        pdf.loadFromFile(file);
        printerJob.setPrintable(pdf, pageFormat);

        //Display the print dialog
        if (printerJob.printDialog()) {
            try {
                printerJob.print();
            } catch (PrinterException e) {
                e.printStackTrace();
            }
        }    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintPDF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintPDF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bike1;
    private javax.swing.JButton bike3;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
